### ISSUE TITLE
Great Plugin but issue with IE11

### ISSUE THREAD

**Issue by jonesrob** [aldocano29/AmandaDocxPrinter#5]
Hi, been playing with your plugin, which is brilliant but when I try and use it in IE11 it will not work, I have even tried your demo application and I have the same problem on the "How To Use the Plugin" page, it will not open due to the JS errors, I have tried Microsoft Edge and Firefox and they work fine but will not open in IE11.

**Comment by aldocano29** [comment]
Internet Explorer uses outdated javascript support which makes it difficult
to work with, since it is so limiting I haven’t tried to make it work there.

TL;DR: AmandaDocxPrinter does not work on IE at the moment
Sorry :(


Sent from Astro <https://www.astro.ai> for Mac

On Sep 7, 2018 at 4:59 PM, jonesrob <notifications@github.com> wrote:


Hi, been playing with your plugin, which is brilliant but when I try and
use it in IE11 it will not work, I have even tried your demo application
and I have the same problem on the "How To Use the Plugin" page, it will
not open due to the JS errors, I have tried Microsoft Edge and Firefox and
they work fine but will not open in IE11.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/aldocano29/AmandaDocxPrinter/issues/5>, or mute the
thread

**Comment by jonesrob** [comment]
Thanks for the quick response, it is what I thought, we are moving over the Edge/Firefox slowly but had a  requirement for IE11, thanks anyway.
